version: "3.8"

services:
  membership-storage-local:
    container_name: local-storage
    image: mysql:8.0.34
    restart: always
    environment:
      - MYSQL_DATABASE=local
      - MYSQL_ROOT_PASSWORD=1234
    ports:
      - '3306:3306'
  membership-storage:
    container_name: membership-storage
    image: mysql:8.0.34
    restart: always
    ports:
      - '3307:3306'
    environment:
      - MYSQL_DATABASE=membership
      - MYSQL_ROOT_PASSWORD=1234
    volumes:
      - ./infra/mysql/membership/initdb.d:/docker-entrypoint-initdb.d
  banking-storage:
    container_name: banking-storage
    image: mysql:8.0.34
    restart: always
    ports:
      - '3308:3306'
    environment:
      - MYSQL_DATABASE=membership
      - MYSQL_ROOT_PASSWORD=1234
    volumes:
      - ./infra/mysql/banking/initdb.d:/docker-entrypoint-initdb.d
  money-storage:
    container_name: money-storage
    image: mysql:8.0.34
    restart: always
    ports:
      - '3309:3306'
    environment:
      - MYSQL_DATABASE=membership
      - MYSQL_ROOT_PASSWORD=1234
    volumes:
      - ./infra/mysql/money/initdb.d:/docker-entrypoint-initdb.d
  membership-service:
    container_name: membership-service
    image: membership-service:latest
    restart: always
    depends_on:
      - membership-storage
    ports:
      - '18080:8080'
    environment:
      - "SPRING_PROFILES_ACTIVE=docker"
networks:
  pay-system-networks:
    driver: bridge