version: "3.8"

services:
  membership-storage-local:
    container_name: local-storage
    image: mysql:8.0.34
    restart: always
    environment:
      - MYSQL_DATABASE=local
      - MYSQL_ROOT_PASSWORD=1234
    ports:
      - '3306:3306'
  membership-storage:
    container_name: membership-storage
    image: mysql:8.0.34
    restart: always
    ports:
      - '3307:3306'
    environment:
      - MYSQL_DATABASE=membership
      - MYSQL_ROOT_PASSWORD=1234
    volumes:
      - ./infra/mysql/membership/initdb.d:/docker-entrypoint-initdb.d
  banking-storage:
    container_name: banking-storage
    image: mysql:8.0.34
    restart: always
    ports:
      - '3308:3306'
    environment:
      - MYSQL_DATABASE=membership
      - MYSQL_ROOT_PASSWORD=1234
    volumes:
      - ./infra/mysql/banking/initdb.d:/docker-entrypoint-initdb.d
  money-storage:
    container_name: money-storage
    image: mysql:8.0.34
    restart: always
    ports:
      - '3309:3306'
    environment:
      - MYSQL_DATABASE=membership
      - MYSQL_ROOT_PASSWORD=1234
    volumes:
      - ./infra/mysql/money/initdb.d:/docker-entrypoint-initdb.d
  membership-service:
    container_name: membership-service
    image: membership-service:latest
    restart: always
    depends_on:
      - membership-storage
      - axon-server
    ports:
      - '18080:8080'
    environment:
      - "SPRING_PROFILES_ACTIVE=docker"
  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    container_name: zookeeper
    networks:
      - pay-system-networks
    environment:
      ZOOKEEPER_SERVER_ID: 1
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
      ZOOKEEPER_INIT_LIMIT: 5
      ZOOKEEPER_SYNC_LIMIT: 2
    ports:
      - "2181:2181"

  kafka:
    image: confluentinc/cp-kafka:latest
    container_name: kafka
    depends_on:
      - zookeeper
    ports:
      - "29092:29092"
      - "9092:9092"
    networks:
      - pay-system-networks
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: 'zookeeper:2181'
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,PLAINTEXT_HOST://localhost:29092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0

  kafka-ui:
    image: provectuslabs/kafka-ui
    container_name: kafka-ui
    networks:
      - pay-system-networks
    ports:
      - "8989:8080"
    restart: always
    depends_on:
      - kafka
      - zookeeper
    environment:
      - KAFKA_CLUSTERS_0_NAME=local
      - KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS=kafka:9092
      - KAFKA_CLUSTERS_0_ZOOKEEPER=zookeeper:2181
  axon-server:
    container_name: axon-server
    image: axoniq/axonserver:4.6.3-jdk-11-dev
    networks:
      - pay-system-networks
    ports:
      - "8024:8024"
      - "8124:8124"

networks:
  pay-system-networks:
    driver: bridge