version: "3.8"

services:
  membership-storage-local:
    container_name: membership-storage-local
    image: mysql:8.0.34
    restart: always
    environment:
      - MYSQL_DATABASE=membership
      - MYSQL_ROOT_PASSWORD=1234
    ports:
      - '3306:3306'
  membership-storage:
    container_name: membership-storage
    image: mysql:8.0.34
    restart: always
    ports:
      - '3307:3306'
    environment:
      - MYSQL_DATABASE=membership
      - MYSQL_ROOT_PASSWORD=1234
    volumes:
      - ./infra/mysql/initdb.d:/docker-entrypoint-initdb.d
  membership-service:
    container_name: membership-service
    image: membership-service:latest
    restart: always
    depends_on:
      - membership-storage
    ports:
      - '8081:8080'
    environment:
      - "SPRING_PROFILES_ACTIVE=docker"
networks:
  pay-system-networks:
    driver: bridge