spring:
  profiles:
    active: local
server:
  port: 8081
kafka:
  clusters:
    bootstrapservers: localhost:29092
logging:
    topic: msa.logging.out.stdout
service:
  membership:
    url: http://membership:8080
axon:
  axonserver:
    servers: localhost:8124
  serializer:
    events: jackson
    messages: jackson
    general: jackson
  deserializer:
    general: jackson
    events: jackson
    messages: jackson
