POST http://localhost:8082/money/increase
Content-Type: application/json

{
  "membershipId": 1,
  "amount": 100000
}

###
POST http://localhost:8082/money/create
Content-Type: application/json

{
  "membershipId": 2
}

###
POST http://localhost:8082/money/increase/axon
Content-Type: application/json

{
"membershipId": 2,
"amount": 100000
}