spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://membership-storage:3306/membership?serverTimezone=UTC&characterEncoding=UTF-8
    username: root
    password: 1234
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    generate-ddl: false
    database: mysql
    hibernate:
      ddl-auto: none
    show-sql: false
    open-in-view: false
